# Generated by Django 3.2.5 on 2021-11-01 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faceregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinhDanhThuCong',
            fields=[
                ('ma_dinh_danh', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField(auto_now=True, null=True)),
                ('chitietlophoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceregister.chitietlophoc')),
            ],
        ),
        migrations.CreateModel(
            name='DinhDanhKhuonMat',
            fields=[
                ('ma_dinh_danh', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duong_dan_anh', models.CharField(max_length=1024, null=True)),
                ('thoi_gian', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(null=True)),
                ('chitietlophoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceregister.chitietlophoc')),
            ],
        ),
    ]
