# Generated by Django 3.2.5 on 2021-11-01 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('magv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mat_khau', models.CharField(max_length=20)),
                ('ho_ten', models.CharField(max_length=50)),
                ('nam_sinh', models.DateField(null=True)),
                ('so_dien_thoai', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LichSuDangNhap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thoi_gian', models.DateTimeField(auto_now=True, null=True)),
                ('tai_khoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.taikhoan')),
            ],
        ),
    ]
