# Generated by Django 3.2.5 on 2021-11-01 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietLopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('masv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=50)),
                ('nam_sinh', models.DateField(null=True)),
                ('so_dien_thoai', models.CharField(max_length=10, null=True)),
                ('gioi_tinh', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('ma_lop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_lop', models.CharField(max_length=50, null=True)),
                ('si_so', models.PositiveSmallIntegerField(null=True)),
                ('model_path', models.CharField(max_length=255, null=True)),
                ('giao_vien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signin.taikhoan')),
                ('sinh_vien', models.ManyToManyField(through='faceregister.ChiTietLopHoc', to='faceregister.SinhVien')),
            ],
        ),
        migrations.AddField(
            model_name='chitietlophoc',
            name='lop_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceregister.lophoc'),
        ),
        migrations.AddField(
            model_name='chitietlophoc',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceregister.sinhvien'),
        ),
        migrations.CreateModel(
            name='AnhDangKy',
            fields=[
                ('ma_anh', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duong_dan_anh', models.CharField(max_length=1024)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceregister.sinhvien')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chitietlophoc',
            constraint=models.UniqueConstraint(fields=('sinh_vien', 'lop_hoc'), name='chitietlophoc_unique'),
        ),
    ]
